package golang_package_name

// generated by lightweight-swagger-codegen@eaglesakura

import (
	"encoding/json"
	"github.com/eaglesakura/swagger-go-core"
	"net/http"
)

//
type Entities struct {
	Hashtags *HashtagsArray `json:"hashtags,omitempty"`

	Media *MediaArray `json:"media,omitempty"`

	Urls *UrlArray `json:"urls,omitempty"`

	UserMentions *UserMentionArray `json:"user_mentions,omitempty"`
}

// encode to json
func (it Entities) String() string {
	buf, _ := json.Marshal(it)
	return string(buf)
}

type EntitiesArray []Entities

func (it *Entities) Valid(factory swagger.ValidatorFactory) bool {
	if !factory.NewValidator(it.Hashtags, it.Hashtags == nil).
		Valid(factory) {
		return false
	}
	if !factory.NewValidator(it.Media, it.Media == nil).
		Valid(factory) {
		return false
	}
	if !factory.NewValidator(it.Urls, it.Urls == nil).
		Valid(factory) {
		return false
	}
	if !factory.NewValidator(it.UserMentions, it.UserMentions == nil).
		Valid(factory) {
		return false
	}

	return true
}

func (it *Entities) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (arr *EntitiesArray) Valid(factory swagger.ValidatorFactory) bool {
	for _, it := range *arr {
		if !factory.NewValidator(it.Hashtags, it.Hashtags == nil).
			Valid(factory) {
			return false
		}
		if !factory.NewValidator(it.Media, it.Media == nil).
			Valid(factory) {
			return false
		}
		if !factory.NewValidator(it.Urls, it.Urls == nil).
			Valid(factory) {
			return false
		}
		if !factory.NewValidator(it.UserMentions, it.UserMentions == nil).
			Valid(factory) {
			return false
		}
	}
	return true
}

func (it *EntitiesArray) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
