package golang_package_name

// generated by lightweight-swagger-codegen@eaglesakura

import (
	"encoding/json"
	"github.com/eaglesakura/swagger-go-core"
	"net/http"
)

//
type Hashtags struct {
	Indices *[]int32 `json:"indices,omitempty"`

	Text *string `json:"text,omitempty"`
}

// encode to json
func (it Hashtags) String() string {
	buf, _ := json.Marshal(it)
	return string(buf)
}

type HashtagsArray []Hashtags

func (it *Hashtags) Valid(factory swagger.ValidatorFactory) bool {
	if !factory.NewValidator(it.Indices, it.Indices == nil).
		Valid(factory) {
		return false
	}
	if !factory.NewValidator(it.Text, it.Text == nil).
		Valid(factory) {
		return false
	}

	return true
}

func (it *Hashtags) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (arr *HashtagsArray) Valid(factory swagger.ValidatorFactory) bool {
	for _, it := range *arr {
		if !factory.NewValidator(it.Indices, it.Indices == nil).
			Valid(factory) {
			return false
		}
		if !factory.NewValidator(it.Text, it.Text == nil).
			Valid(factory) {
			return false
		}
	}
	return true
}

func (it *HashtagsArray) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
