package golang_package_name

// generated by lightweight-swagger-codegen@eaglesakura

import (
	"encoding/json"
	"github.com/eaglesakura/swagger-go-core"
	"net/http"
)

//
type PlaceType struct {
	Name *string `json:"name,omitempty"`

	Code *int32 `json:"code,omitempty"`
}

// encode to json
func (it PlaceType) String() string {
	buf, _ := json.Marshal(it)
	return string(buf)
}

type PlaceTypeArray []PlaceType

func (it *PlaceType) Valid(factory swagger.ValidatorFactory) bool {
	if !factory.NewValidator(it.Name, it.Name == nil).
		Valid(factory) {
		return false
	}
	if !factory.NewValidator(it.Code, it.Code == nil).
		Valid(factory) {
		return false
	}

	return true
}

func (it *PlaceType) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (arr *PlaceTypeArray) Valid(factory swagger.ValidatorFactory) bool {
	for _, it := range *arr {
		if !factory.NewValidator(it.Name, it.Name == nil).
			Valid(factory) {
			return false
		}
		if !factory.NewValidator(it.Code, it.Code == nil).
			Valid(factory) {
			return false
		}
	}
	return true
}

func (it *PlaceTypeArray) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
