package golang_package_name

// generated by lightweight-swagger-codegen@eaglesakura

import (
	"encoding/json"
	"github.com/eaglesakura/swagger-go-core"
	"net/http"
)

//
type BoundingBox struct {
	Coordinates *[]float32Array `json:"coordinates,omitempty"`

	Type_ *string `json:"type,omitempty"`
}

// encode to json
func (it BoundingBox) String() string {
	buf, _ := json.Marshal(it)
	return string(buf)
}

type BoundingBoxArray []BoundingBox

func (it *BoundingBox) Valid(factory swagger.ValidatorFactory) bool {
	if !factory.NewValidator(it.Coordinates, it.Coordinates == nil).
		Valid(factory) {
		return false
	}
	if !factory.NewValidator(it.Type_, it.Type_ == nil).
		Valid(factory) {
		return false
	}

	return true
}

func (it *BoundingBox) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (arr *BoundingBoxArray) Valid(factory swagger.ValidatorFactory) bool {
	for _, it := range *arr {
		if !factory.NewValidator(it.Coordinates, it.Coordinates == nil).
			Valid(factory) {
			return false
		}
		if !factory.NewValidator(it.Type_, it.Type_ == nil).
			Valid(factory) {
			return false
		}
	}
	return true
}

func (it *BoundingBoxArray) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
