package golang_package_name

// generated by lightweight-swagger-codegen@eaglesakura

import (
	"encoding/json"
	"github.com/eaglesakura/swagger-go-core"
	"net/http"
)

//
type Url struct {
	DisplayUrl *string `json:"display_url,omitempty"`

	ExpandedUrl *string `json:"expanded_url,omitempty"`

	Indices *string `json:"indices,omitempty"`

	Url *string `json:"url,omitempty"`
}

// encode to json
func (it Url) String() string {
	buf, _ := json.Marshal(it)
	return string(buf)
}

type UrlArray []Url

func (it *Url) Valid(factory swagger.ValidatorFactory) bool {
	if !factory.NewValidator(it.DisplayUrl, it.DisplayUrl == nil).
		Valid(factory) {
		return false
	}
	if !factory.NewValidator(it.ExpandedUrl, it.ExpandedUrl == nil).
		Valid(factory) {
		return false
	}
	if !factory.NewValidator(it.Indices, it.Indices == nil).
		Valid(factory) {
		return false
	}
	if !factory.NewValidator(it.Url, it.Url == nil).
		Valid(factory) {
		return false
	}

	return true
}

func (it *Url) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (arr *UrlArray) Valid(factory swagger.ValidatorFactory) bool {
	for _, it := range *arr {
		if !factory.NewValidator(it.DisplayUrl, it.DisplayUrl == nil).
			Valid(factory) {
			return false
		}
		if !factory.NewValidator(it.ExpandedUrl, it.ExpandedUrl == nil).
			Valid(factory) {
			return false
		}
		if !factory.NewValidator(it.Indices, it.Indices == nil).
			Valid(factory) {
			return false
		}
		if !factory.NewValidator(it.Url, it.Url == nil).
			Valid(factory) {
			return false
		}
	}
	return true
}

func (it *UrlArray) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
