package golang_package_name

// generated by lightweight-swagger-codegen@eaglesakura

import (
	"encoding/json"
	"github.com/eaglesakura/swagger-go-core"
	"net/http"
)

//
type Size struct {
	H *int32 `json:"h,omitempty"`

	Resize *string `json:"resize,omitempty"`

	W *int32 `json:"w,omitempty"`
}

// encode to json
func (it Size) String() string {
	buf, _ := json.Marshal(it)
	return string(buf)
}

type SizeArray []Size

func (it *Size) Valid(factory swagger.ValidatorFactory) bool {
	if !factory.NewValidator(it.H, it.H == nil).
		Valid(factory) {
		return false
	}
	if !factory.NewValidator(it.Resize, it.Resize == nil).
		Valid(factory) {
		return false
	}
	if !factory.NewValidator(it.W, it.W == nil).
		Valid(factory) {
		return false
	}

	return true
}

func (it *Size) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (arr *SizeArray) Valid(factory swagger.ValidatorFactory) bool {
	for _, it := range *arr {
		if !factory.NewValidator(it.H, it.H == nil).
			Valid(factory) {
			return false
		}
		if !factory.NewValidator(it.Resize, it.Resize == nil).
			Valid(factory) {
			return false
		}
		if !factory.NewValidator(it.W, it.W == nil).
			Valid(factory) {
			return false
		}
	}
	return true
}

func (it *SizeArray) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
