package golang_package_name

// generated by lightweight-swagger-codegen@eaglesakura

import (
	"encoding/json"
	"github.com/eaglesakura/swagger-go-core"
	"net/http"
)

//
type TrendInfo struct {
	AsOf *string `json:"as_of,omitempty"`

	CreatedAt *string `json:"created_at,omitempty"`

	Locations *LocationArray `json:"locations,omitempty"`

	Trends *TrendsArray `json:"trends,omitempty"`
}

// encode to json
func (it TrendInfo) String() string {
	buf, _ := json.Marshal(it)
	return string(buf)
}

type TrendInfoArray []TrendInfo

func (it *TrendInfo) Valid(factory swagger.ValidatorFactory) bool {
	if !factory.NewValidator(it.AsOf, it.AsOf == nil).
		Valid(factory) {
		return false
	}
	if !factory.NewValidator(it.CreatedAt, it.CreatedAt == nil).
		Valid(factory) {
		return false
	}
	if !factory.NewValidator(it.Locations, it.Locations == nil).
		Valid(factory) {
		return false
	}
	if !factory.NewValidator(it.Trends, it.Trends == nil).
		Valid(factory) {
		return false
	}

	return true
}

func (it *TrendInfo) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (arr *TrendInfoArray) Valid(factory swagger.ValidatorFactory) bool {
	for _, it := range *arr {
		if !factory.NewValidator(it.AsOf, it.AsOf == nil).
			Valid(factory) {
			return false
		}
		if !factory.NewValidator(it.CreatedAt, it.CreatedAt == nil).
			Valid(factory) {
			return false
		}
		if !factory.NewValidator(it.Locations, it.Locations == nil).
			Valid(factory) {
			return false
		}
		if !factory.NewValidator(it.Trends, it.Trends == nil).
			Valid(factory) {
			return false
		}
	}
	return true
}

func (it *TrendInfoArray) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
