package golang_package_name

// generated by lightweight-swagger-codegen@eaglesakura

import (
	"encoding/json"
	"github.com/eaglesakura/swagger-go-core"
	"net/http"
)

//
type HelpPrivacy struct {
	Privacy *string `json:"privacy,omitempty"`
}

// encode to json
func (it HelpPrivacy) String() string {
	buf, _ := json.Marshal(it)
	return string(buf)
}

type HelpPrivacyArray []HelpPrivacy

func (it *HelpPrivacy) Valid(factory swagger.ValidatorFactory) bool {
	if !factory.NewValidator(it.Privacy, it.Privacy == nil).
		Valid(factory) {
		return false
	}

	return true
}

func (it *HelpPrivacy) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (arr *HelpPrivacyArray) Valid(factory swagger.ValidatorFactory) bool {
	for _, it := range *arr {
		if !factory.NewValidator(it.Privacy, it.Privacy == nil).
			Valid(factory) {
			return false
		}
	}
	return true
}

func (it *HelpPrivacyArray) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
