package golang_package_name

// generated by lightweight-swagger-codegen@eaglesakura

import (
	"encoding/json"
	"github.com/eaglesakura/swagger-go-core"
	"net/http"
)

//
type Friendship struct {
	Relationship *Targets `json:"relationship,omitempty"`

	Source *Source `json:"source,omitempty"`
}

// encode to json
func (it Friendship) String() string {
	buf, _ := json.Marshal(it)
	return string(buf)
}

type FriendshipArray []Friendship

func (it *Friendship) Valid(factory swagger.ValidatorFactory) bool {
	if !factory.NewValidator(it.Relationship, it.Relationship == nil).
		Valid(factory) {
		return false
	}
	if !factory.NewValidator(it.Source, it.Source == nil).
		Valid(factory) {
		return false
	}

	return true
}

func (it *Friendship) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (arr *FriendshipArray) Valid(factory swagger.ValidatorFactory) bool {
	for _, it := range *arr {
		if !factory.NewValidator(it.Relationship, it.Relationship == nil).
			Valid(factory) {
			return false
		}
		if !factory.NewValidator(it.Source, it.Source == nil).
			Valid(factory) {
			return false
		}
	}
	return true
}

func (it *FriendshipArray) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
