package golang_package_name

// generated by lightweight-swagger-codegen@eaglesakura

import (
	"encoding/json"
	"github.com/eaglesakura/swagger-go-core"
	"net/http"
)

//
type HelpTos struct {
	Tos *string `json:"Tos,omitempty"`
}

// encode to json
func (it HelpTos) String() string {
	buf, _ := json.Marshal(it)
	return string(buf)
}

type HelpTosArray []HelpTos

func (it *HelpTos) Valid(factory swagger.ValidatorFactory) bool {
	if !factory.NewValidator(it.Tos, it.Tos == nil).
		Valid(factory) {
		return false
	}

	return true
}

func (it *HelpTos) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (arr *HelpTosArray) Valid(factory swagger.ValidatorFactory) bool {
	for _, it := range *arr {
		if !factory.NewValidator(it.Tos, it.Tos == nil).
			Valid(factory) {
			return false
		}
	}
	return true
}

func (it *HelpTosArray) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
