package golang_package_name

// generated by lightweight-swagger-codegen@eaglesakura

import (
	"encoding/json"
	"github.com/eaglesakura/swagger-go-core"
	"net/http"
)

//
type Sizes struct {
	Thumb *Size `json:"thumb,omitempty"`

	Large *Size `json:"large,omitempty"`

	Medium *Size `json:"medium,omitempty"`

	Small *Size `json:"small,omitempty"`
}

// encode to json
func (it Sizes) String() string {
	buf, _ := json.Marshal(it)
	return string(buf)
}

type SizesArray []Sizes

func (it *Sizes) Valid(factory swagger.ValidatorFactory) bool {
	if !factory.NewValidator(it.Thumb, it.Thumb == nil).
		Valid(factory) {
		return false
	}
	if !factory.NewValidator(it.Large, it.Large == nil).
		Valid(factory) {
		return false
	}
	if !factory.NewValidator(it.Medium, it.Medium == nil).
		Valid(factory) {
		return false
	}
	if !factory.NewValidator(it.Small, it.Small == nil).
		Valid(factory) {
		return false
	}

	return true
}

func (it *Sizes) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (arr *SizesArray) Valid(factory swagger.ValidatorFactory) bool {
	for _, it := range *arr {
		if !factory.NewValidator(it.Thumb, it.Thumb == nil).
			Valid(factory) {
			return false
		}
		if !factory.NewValidator(it.Large, it.Large == nil).
			Valid(factory) {
			return false
		}
		if !factory.NewValidator(it.Medium, it.Medium == nil).
			Valid(factory) {
			return false
		}
		if !factory.NewValidator(it.Small, it.Small == nil).
			Valid(factory) {
			return false
		}
	}
	return true
}

func (it *SizesArray) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
