package golang_package_name

// generated by lightweight-swagger-codegen@eaglesakura

import (
	"encoding/json"
	"github.com/eaglesakura/swagger-go-core"
	"net/http"
)

//
type HelpLanguage struct {
	Code *string `json:"code,omitempty"`

	Status *string `json:"status,omitempty"`

	Name *string `json:"name,omitempty"`
}

// encode to json
func (it HelpLanguage) String() string {
	buf, _ := json.Marshal(it)
	return string(buf)
}

type HelpLanguageArray []HelpLanguage

func (it *HelpLanguage) Valid(factory swagger.ValidatorFactory) bool {
	if !factory.NewValidator(it.Code, it.Code == nil).
		Valid(factory) {
		return false
	}
	if !factory.NewValidator(it.Status, it.Status == nil).
		Valid(factory) {
		return false
	}
	if !factory.NewValidator(it.Name, it.Name == nil).
		Valid(factory) {
		return false
	}

	return true
}

func (it *HelpLanguage) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (arr *HelpLanguageArray) Valid(factory swagger.ValidatorFactory) bool {
	for _, it := range *arr {
		if !factory.NewValidator(it.Code, it.Code == nil).
			Valid(factory) {
			return false
		}
		if !factory.NewValidator(it.Status, it.Status == nil).
			Valid(factory) {
			return false
		}
		if !factory.NewValidator(it.Name, it.Name == nil).
			Valid(factory) {
			return false
		}
	}
	return true
}

func (it *HelpLanguageArray) WriteResponse(writer http.ResponseWriter, producer swagger.Producer) {
	writer.WriteHeader(200)
	if err := producer.Produce(writer, it); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
